name: Update YouTube Videos

on:
  schedule:
    - cron: "0 3 */3 * *" # cada 3 dias a las 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Call Astro endpoint
        run: |
          curl -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          https://dandelion-rho.vercel.app/api/update-youtube-videos
